// ======================================================
// Elola ERP Enterprise
// Product Engine
// ======================================================

import ProductsRepository
  from '../../../repositories/ProductsRepository'

import InventoryRepository
  from '../../../repositories/InventoryRepository'

// ======================================================
// REMOVE UNDEFINED VALUES
// ======================================================

const removeUndefined = (value) => {

  if (Array.isArray(value)) {

    return value
      .map(item =>
        removeUndefined(item)
      )
      .filter(item =>
        item !== undefined
      )

  }


  if (
    value &&
    typeof value === 'object' &&
    !(value instanceof Date)
  ) {

    const result = {}


    Object.entries(value).forEach(
      ([key, item]) => {

        if (
          item !== undefined
        ) {

          result[key] =
            removeUndefined(item)

        }

      }
    )


    return result

  }


  return value

}


class ProductEngine {


  // ======================================================
  // NORMALIZE PRODUCT
  // ======================================================

  normalize(product = {}) {

    const purchasePrice =
      Number(
        product.purchasePrice || 0
      )


    const salePrice =
      Number(
        product.salePrice || 0
      )


    const profit =
      salePrice -
      purchasePrice


    const profitMargin =
      salePrice > 0
        ? (
            profit /
            salePrice
          ) * 100
        : 0


    return removeUndefined({

      ...product,

      purchasePrice,

      salePrice,

      averagePurchasePrice:
        Number(
          product.averagePurchasePrice ??
          purchasePrice
        ),

      profit,

      profitMargin,

      compatibleVehicles:
        Array.isArray(
          product.compatibleVehicles
        )
          ? product.compatibleVehicles
          : [],

      active:
        product.active ??
        true

    })

  }


  // ======================================================
  // VALIDATE PRODUCT
  // ======================================================

  validate(product = {}) {

    const errors = []


    if (
      !String(
        product.name ||
        product.productName ||
        ''
      ).trim()
    ) {

      errors.push(
        'اسم المنتج مطلوب'
      )

    }


    if (
      Number(
        product.salePrice || 0
      ) < 0
    ) {

      errors.push(
        'سعر البيع غير صحيح'
      )

    }


    if (
      Number(
        product.purchasePrice || 0
      ) < 0
    ) {

      errors.push(
        'سعر الشراء غير صحيح'
      )

    }


    return {

      valid:
        errors.length === 0,

      errors

    }

  }


  // ======================================================
  // CREATE PRODUCT
  // ======================================================

  async create(product = {}) {

    const validation =
      this.validate(product)


    if (
      !validation.valid
    ) {

      return {

        success: false,

        data: null,

        message:
          'بيانات المنتج غير صحيحة',

        errors:
          validation.errors

      }

    }


    const normalized =
      this.normalize(product)


    const {

      warehouseId,

      quantity = 0,

      minimumStock = 0,

      maximumStock = 0,

      reorderPoint = 0,

      id: ignoredId,

      productId: ignoredProductId,

      ...rawProductData

    } = normalized


    // ====================================================
    // PRODUCT DATA
    // ====================================================
    // Firestore document ID is generated by BaseRepository.
    // We MUST NOT send id/productId as undefined.
    // ====================================================

    const productData =
      removeUndefined({

        ...rawProductData,

        quantity:
          undefined,

        minimumStock:
          undefined,

        maximumStock:
          undefined,

        reorderPoint:
          undefined

      })


    // ====================================================
    // CREATE PRODUCT IN FIRESTORE
    // ====================================================

    const createdProduct =
      await ProductsRepository.create(
        productData
      )


    if (
      !createdProduct?.success
    ) {

      return {

        success: false,

        data: null,

        message:
          createdProduct?.message ||
          'فشل إنشاء المنتج',

        errors:
          createdProduct?.errors || []

      }

    }


    const productId =
      createdProduct
        ?.data
        ?.id


    if (!productId) {

      return {

        success: false,

        data: null,

        message:
          'تم إنشاء المنتج ولكن لم يتم الحصول على معرف المنتج',

        errors: []

      }

    }


    // ====================================================
    // CREATE INITIAL WAREHOUSE INVENTORY
    // ====================================================

    if (warehouseId) {

      const inventoryResult =
        await InventoryRepository.create({

          productId,

          warehouseId,

          quantity:
            Number(
              quantity || 0
            ),

          minimumStock:
            Number(
              minimumStock || 0
            ),

          maximumStock:
            Number(
              maximumStock || 0
            ),

          reorderPoint:
            Number(
              reorderPoint || 0
            ),

          purchasePrice:
            Number(
              normalized.purchasePrice || 0
            ),

          salePrice:
            Number(
              normalized.salePrice || 0
            )

        })


      if (
        !inventoryResult?.success
      ) {

        console.error(
          'ProductEngine.create inventory failed:',
          inventoryResult?.message,
          inventoryResult?.errors
        )


        return {

          success: false,

          data: {

            productId,

            inventoryCreated:
              false

          },

          message:
            'تم إنشاء المنتج ولكن فشل إنشاء مخزون المخزن',

          errors:
            inventoryResult?.errors || []

        }

      }

    }


    // ====================================================
    // RETURN
    // ====================================================

    return {

      success: true,

      data: {

        ...productData,

        id:
          productId

      },

      message:
        'تم إنشاء المنتج بنجاح',

      errors: []

    }

  }


  // ======================================================
  // UPDATE PRODUCT
  // ======================================================

  async update(
    id,
    product = {}
  ) {

    if (!id) {

      return {

        success: false,

        data: null,

        message:
          'معرف المنتج مطلوب',

        errors: []

      }

    }


    const normalized =
      this.normalize(product)


    const {

      warehouseId,

      quantity,

      minimumStock,

      maximumStock,

      reorderPoint,

      id: ignoredId,

      productId: ignoredProductId,

      ...rawProductData

    } = normalized


    const productData =
      removeUndefined(
        rawProductData
      )


    // ====================================================
    // UPDATE PRODUCT
    // ====================================================

    const productResult =
      await ProductsRepository.update(

        id,

        productData

      )


    if (
      !productResult?.success
    ) {

      return productResult

    }


    // ====================================================
    // UPDATE INVENTORY
    // ====================================================

    if (warehouseId) {

      const inventory =
        await InventoryRepository
          .getByProductAndWarehouse(

            id,

            warehouseId

          )


      if (inventory) {

        const inventoryData = {}


        if (
          quantity !== undefined
        ) {

          inventoryData.quantity =
            Number(quantity)

        }


        if (
          minimumStock !== undefined
        ) {

          inventoryData.minimumStock =
            Number(
              minimumStock
            )

        }


        if (
          maximumStock !== undefined
        ) {

          inventoryData.maximumStock =
            Number(
              maximumStock
            )

        }


        if (
          reorderPoint !== undefined
        ) {

          inventoryData.reorderPoint =
            Number(
              reorderPoint
            )

        }


        if (
          Object.keys(
            inventoryData
          ).length > 0
        ) {

          await InventoryRepository.update(

            inventory.id,

            inventoryData

          )

        }

      }

    }


    return productResult

  }


  // ======================================================
  // DELETE PRODUCT
  // ======================================================

  async delete(id) {

    return await ProductsRepository.delete(
      id
    )

  }


  // ======================================================
  // GET ALL
  // ======================================================

  async getAll() {

    return await ProductsRepository.getAll()

  }


  // ======================================================
  // GET BY ID
  // ======================================================

  async getById(id) {

    return await ProductsRepository.getById(
      id
    )

  }


  // ======================================================
  // GET PRODUCT INVENTORY
  // ======================================================

  async getInventory(productId) {

    return await InventoryRepository
      .getByProduct(
        productId
      )

  }


  // ======================================================
  // GET WAREHOUSE INVENTORY
  // ======================================================

  async getWarehouseInventory(
    warehouseId
  ) {

    return await InventoryRepository
      .getByWarehouse(
        warehouseId
      )

  }


  // ======================================================
  // GET PRODUCT STOCK IN WAREHOUSE
  // ======================================================

  async getStock(
    productId,
    warehouseId
  ) {

    return await InventoryRepository
      .getByProductAndWarehouse(

        productId,

        warehouseId

      )

  }


  // ======================================================
  // INCREASE STOCK
  // ======================================================

  async increaseStock(

    productId,

    warehouseId,

    quantity

  ) {

    if (
      !productId ||
      !warehouseId ||
      Number(quantity) <= 0
    ) {

      return {

        success: false,

        data: null,

        message:
          'بيانات زيادة المخزون غير صحيحة',

        errors: []

      }

    }


    const amount =
      Number(quantity)


    let inventory =
      await InventoryRepository
        .getByProductAndWarehouse(

          productId,

          warehouseId

        )


    // ====================================================
    // CREATE INVENTORY IF MISSING
    // ====================================================

    if (!inventory) {

      const product =
        await ProductsRepository.getById(
          productId
        )


      if (
        !product
      ) {

        return {

          success: false,

          data: null,

          message:
            'المنتج غير موجود',

          errors: []

        }

      }


      const created =
        await InventoryRepository.create({

          productId,

          warehouseId,

          quantity:
            amount,

          purchasePrice:
            Number(
              product.purchasePrice || 0
            ),

          salePrice:
            Number(
              product.salePrice || 0
            )

        })


      if (
        !created?.success
      ) {

        return created

      }


      return {

        success: true,

        data: {

          inventoryId:
            created.data.id,

          productId,

          warehouseId,

          quantity:
            amount

        }

      }

    }


    // ====================================================
    // UPDATE EXISTING INVENTORY
    // ====================================================

    const result =
      await InventoryRepository
        .increaseStock(

          inventory.id,

          amount

        )


    return result

  }


  // ======================================================
  // DECREASE STOCK
  // ======================================================

  async decreaseStock(

    productId,

    warehouseId,

    quantity

  ) {

    if (
      !productId ||
      !warehouseId ||
      Number(quantity) <= 0
    ) {

      return {

        success: false,

        data: null,

        message:
          'بيانات نقص المخزون غير صحيحة',

        errors: []

      }

    }


    const amount =
      Number(quantity)


    const inventory =
      await InventoryRepository
        .getByProductAndWarehouse(

          productId,

          warehouseId

        )


    if (!inventory) {

      return {

        success: false,

        data: null,

        message:
          'لا يوجد مخزون لهذا المنتج في هذا المخزن',

        errors: []

      }

    }


    const current =
      Number(
        inventory.quantity || 0
      )


    if (
      current < amount
    ) {

      return {

        success: false,

        data: null,

        message:
          'الكمية المطلوبة أكبر من المخزون المتاح',

        errors: []

      }

    }


    return await InventoryRepository
      .decreaseStock(

        inventory.id,

        amount

      )

  }

}


export default new ProductEngine()